# Appium Server Configuration
appiumURL=http://127.0.0.1:4723

# Android Capabilities
androidPlatformName=Android
androidAutomationName=UiAutomator2
androidUDID= your-device-udid-here
androidDeviceName=MyAndroidDevice
androidAppPackage=com.swaglabsmobileapp
androidAppActivity=com.swaglabsmobileapp.SplashActivity
androidAppLocation=src/main/resources/app/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk

# iOS Capabilities (optional, for future use)
iOSPlatformName=iOS
iOSAutomationName=XCUITest
iOSBundleId=
iOSAppLocation=src/test/resources/app/SwagLabsMobileApp.app